# Generated by Django 5.0.3 on 2024-04-01 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_listing_comment_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchers",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
